'use client';

import Link from 'next/link';
import { Suspense, useCallback, useEffect, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import AccessibleDialog from '@/components/AccessibleDialog';
import AdminLayout from '@/components/AdminLayout';
import LessonForm from '@/components/LessonForm';
import { adminCourses, adminLessons, type AdminCourse, type AdminLesson, type LessonWrite, type PageMeta } from '@/lib/api';

const blank = (courseId = 0): LessonWrite => ({ course_id: courseId, title: '', slug: '', content: '', sort_order: 0, estimated_minutes: 10, status: 'draft' });

export default function LessonsPage() { return <AdminLayout title="Lessons"><Suspense fallback={<p>Loading lessons…</p>}><Content /></Suspense></AdminLayout>; }

function Content() {
  const query = useSearchParams(), router = useRouter(), pathname = usePathname();
  const [items, setItems] = useState<AdminLesson[]>([]), [courses, setCourses] = useState<AdminCourse[]>([]), [editing, setEditing] = useState<AdminLesson | null | undefined>(), [meta, setMeta] = useState<PageMeta>(), [message, setMessage] = useState(''), [loading, setLoading] = useState(true);
  const courseId = Number(query.get('course_id') || 0), search = query.get('search') || '', status = query.get('status') || '', page = Number(query.get('page') || 1), mode = query.get('mode');
  const setQuery = useCallback((patch: Record<string, string>) => { const next = new URLSearchParams(query); Object.entries(patch).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); router.replace(`${pathname}?${next}`); }, [pathname, query, router]);
  const load = useCallback(async () => { setLoading(true); setMessage(''); try { const [lessons, coursePage] = await Promise.all([adminLessons.list({ search, courseId: courseId || undefined, status: status || undefined, page }), adminCourses.list()]); setItems(lessons.data); setMeta(lessons.meta); setCourses(coursePage.data); const id = Number(query.get('lesson') || 0); if (mode === 'create') setEditing(null); else if (id) setEditing(await adminLessons.get(id)); else setEditing(undefined); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load lessons.'); } finally { setLoading(false); } }, [courseId, mode, page, query, search, status]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function save(data: LessonWrite) { if (editing?.id) await adminLessons.update(editing.id, data); else await adminLessons.create(data); setQuery({ lesson: '', mode: '' }); await load(); }
  async function act(item: AdminLesson, action: 'publish' | 'archive' | 'delete') { if (action === 'delete' && !confirm(`Delete lesson “${item.title}”?`)) return; try { await (action === 'delete' ? adminLessons.delete(item.id) : adminLessons[action](item.id)); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : `Could not ${action} lesson.`); } }
  const close = () => { setEditing(undefined); setQuery({ lesson: '', mode: '' }); };

  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#006590]">Course authoring</p><h1 className="mt-2 text-3xl font-black">Lessons</h1><p className="text-[#3e4850]">Arrange focused learning units and their checkpoints.</p></div><button onClick={() => setQuery({ mode: 'create', lesson: '' })} className="rounded-xl bg-[#006590] px-5 py-3 font-black text-white">New lesson</button></header>
    {message && <p role="alert" className="rounded-xl bg-[#ffdf92] p-3">{message}</p>}
    <div className="grid gap-3 rounded-2xl border-2 border-[#bdc8d2] bg-white p-4 md:grid-cols-3"><input aria-label="Search lessons" value={search} onChange={event => setQuery({ search: event.target.value, page: '' })} placeholder="Search lessons…" className="rounded-xl border-2 border-[#bdc8d2] p-3"/><select aria-label="Filter by course" value={courseId || ''} onChange={event => setQuery({ course_id: event.target.value, page: '' })} className="rounded-xl border-2 border-[#bdc8d2] p-3"><option value="">All courses</option>{courses.map(course => <option key={course.id} value={course.id}>{course.title}</option>)}</select><select aria-label="Filter by status" value={status} onChange={event => setQuery({ status: event.target.value, page: '' })} className="rounded-xl border-2 border-[#bdc8d2] p-3"><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div>
    <section className="overflow-hidden rounded-3xl border-2 border-[#bdc8d2] bg-white">{loading ? <p className="p-10 text-center">Loading…</p> : items.length === 0 ? <p className="p-10 text-center">No lessons found.</p> : <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr>{['Lesson', 'Course', 'Status', 'Content', 'Actions'].map(label => <th key={label} className="p-4 text-xs uppercase">{label}</th>)}</tr></thead><tbody>{items.map(item => <tr key={item.id} className="border-t"><td className="p-4"><strong>{item.title}</strong><small className="block text-[#6e7881]">{item.slug}</small></td><td className="p-4">{item.course.title}</td><td className="p-4">{item.status}</td><td className="p-4">{item.vocabularies_count} words · {item.quizzes_count} quizzes</td><td className="p-4"><div className="flex flex-wrap gap-2"><button onClick={() => setQuery({ lesson: String(item.id), mode: 'view' })}>View</button><button onClick={() => setQuery({ lesson: String(item.id), mode: 'edit' })} className="text-[#006590]">Edit</button><Link href={`/quiz-management?lesson_id=${item.id}&mode=create`}>Quiz</Link>{item.status === 'draft' && <button onClick={() => void act(item, 'publish')} className="text-[#006590]">Publish</button>}{item.status !== 'archived' && <button onClick={() => void act(item, 'archive')}>Archive</button>}<button onClick={() => void act(item, 'delete')} className="text-[#ba1a1a]">Delete</button></div></td></tr>)}</tbody></table></div>}</section>
    <nav aria-label="Lesson pages" className="flex justify-center gap-3"><button disabled={page <= 1} onClick={() => setQuery({ page: String(page - 1) })}>Previous</button><span>{page}/{meta?.last_page ?? 1}</span><button disabled={page >= (meta?.last_page ?? 1)} onClick={() => setQuery({ page: String(page + 1) })}>Next</button></nav>
    {editing && mode === 'view' && <AccessibleDialog title={editing.title} onClose={close} className="max-w-xl"><p className="mt-2 text-[#3e4850]">{editing.course.title} · {editing.status} · {editing.estimated_minutes ?? 0} minutes</p><div className="mt-5 whitespace-pre-wrap rounded-xl bg-[#f5f3f3] p-4">{editing.content || 'No content.'}</div><button onClick={close} className="mt-6 rounded-xl border-2 px-5 py-3 font-bold">Close</button></AccessibleDialog>}
    {editing !== undefined && mode !== 'view' && <LessonForm initial={editing ? { course_id: editing.course.id, title: editing.title, slug: editing.slug, content: editing.content, sort_order: editing.sort_order, estimated_minutes: editing.estimated_minutes, status: editing.status } : blank(courseId)} courses={courses} onSave={save} onClose={close}/>} 
  </div>;
}
