'use client';

import { useCallback, useEffect, useState } from 'react';
import AdminLayout from '@/components/AdminLayout';
import { DataPanel, PageHeading, StateNotice } from '@/components/AdminDataView';
import { operations, type AuditEvent, type PageMeta } from '@/lib/api';

export default function AuditLogsPage() { return <AdminLayout title="Audit Logs" requiredRole="super_admin"><PageContent /></AdminLayout>; }
function PageContent() {
  const [items, setItems] = useState<AuditEvent[]>(); const [meta, setMeta] = useState<PageMeta>(); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [action, setAction] = useState(''); const [page, setPage] = useState(1);
  const load = useCallback(async () => { setError(''); try { const result = await operations.audits({ search: search || undefined, action: action || undefined, page, perPage: 20 }); setItems(result.data); setMeta(result.meta); } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tải audit trail.'); } }, [action, page, search]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  return <div className="space-y-6"><PageHeading eyebrow="Super admin only" title="Audit trail" description="Dữ liệu bất biến từ server; bộ lọc được thực thi phía backend." /><form onSubmit={(event) => { event.preventDefault(); setPage(1); void load(); }} className="flex flex-wrap gap-3"><input aria-label="Search audit logs" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Action, target type hoặc target id" className="min-w-64 flex-1 rounded-xl border-2 border-[#bdc8d2] bg-white px-4 py-3" /><input aria-label="Filter action" value={action} onChange={(event) => setAction(event.target.value)} placeholder="Exact action" className="rounded-xl border-2 border-[#bdc8d2] bg-white px-4 py-3" /><button className="rounded-xl bg-[#006590] px-5 py-3 font-bold text-white">Lọc</button></form>{error && !items ? <StateNotice state="error" message={error} retry={load} /> : !items ? <StateNotice state="loading" /> : <DataPanel title={`Events · ${meta?.total ?? items.length}`}>{error && <p role="alert" className="mb-4 rounded-xl bg-[#ffdad6] p-4 font-bold text-[#93000a]">{error}</p>}{items.length === 0 ? <StateNotice state="empty" message="Không có audit event phù hợp." /> : <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th className="p-3">Action</th><th className="p-3">Actor</th><th className="p-3">Target</th><th className="p-3">Time</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t"><td className="p-3 font-bold text-[#006590]">{item.action}</td><td className="p-3">{item.actor?.email ?? 'System'}</td><td className="p-3">{[item.target_type, item.target_id].filter(Boolean).join(' #') || '—'}</td><td className="p-3"><time dateTime={item.occurred_at}>{new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(item.occurred_at))}</time></td></tr>)}</tbody></table></div>}<div className="mt-5 flex justify-end gap-3"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded-xl border-2 border-[#bdc8d2] px-4 py-2 font-bold disabled:opacity-40">Trước</button><span className="py-2 font-bold">{page}</span><button disabled={items.length < 20} onClick={() => setPage((value) => value + 1)} className="rounded-xl border-2 border-[#bdc8d2] px-4 py-2 font-bold disabled:opacity-40">Sau</button></div></DataPanel>}</div>;
}
