'use client';

import { useState } from 'react';
import type { AdminCourse, LessonWrite } from '@/lib/api';
import AccessibleDialog from '@/components/AccessibleDialog';

export default function LessonForm({ initial, courses, onSave, onClose }: { initial: LessonWrite; courses: AdminCourse[]; onSave: (value: LessonWrite) => Promise<void>; onClose: () => void }) {
  const [form, setForm] = useState(initial); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { await onSave(form); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save lesson.'); } finally { setSaving(false); } }
  return <AccessibleDialog title={initial.title ? 'Edit lesson' : 'New lesson'} onClose={onClose}><form onSubmit={submit}>{error && <p role="alert" className="mt-4 rounded-xl bg-[#ffdad6] p-3 text-[#93000a]">{error}</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Course"><select required value={form.course_id || ''} onChange={e => setForm({...form, course_id:Number(e.target.value)})}><option value="">Select course</option>{courses.map(course => <option key={course.id} value={course.id}>{course.title}</option>)}</select></Field><Field label="Title"><input required value={form.title} onChange={e => setForm({...form,title:e.target.value})}/></Field><Field label="Slug"><input required value={form.slug} onChange={e => setForm({...form,slug:e.target.value})}/></Field><Field label="Order"><input required min="0" type="number" value={form.sort_order} onChange={e => setForm({...form,sort_order:Number(e.target.value)})}/></Field><Field label="Minutes"><input min="1" type="number" value={form.estimated_minutes ?? ''} onChange={e => setForm({...form,estimated_minutes:e.target.value ? Number(e.target.value) : null})}/></Field>{!initial.title && <Field label="Status"><select value={form.status} onChange={e => setForm({...form,status:e.target.value as LessonWrite['status']})}><option value="draft">Draft</option><option value="published">Published</option></select></Field>}</div><label className="mt-4 block font-bold">Content<textarea rows={7} value={form.content ?? ''} onChange={e => setForm({...form,content:e.target.value})} className="mt-2 w-full rounded-xl border-2 border-[#bdc8d2] p-3"/></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl px-5 py-3 font-bold">Cancel</button><button disabled={saving} className="rounded-xl bg-[#006590] px-5 py-3 font-black text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save lesson'}</button></div></form></AccessibleDialog>;
}
function Field({label,children}:{label:string;children:React.ReactElement}) { return <label className="font-bold">{label}<span className="mt-2 block [&>*]:w-full [&>*]:rounded-xl [&>*]:border-2 [&>*]:border-[#bdc8d2] [&>*]:p-3">{children}</span></label>; }
