'use client';

import Link from 'next/link';
import { Suspense, useCallback, useEffect, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import AccessibleDialog from '@/components/AccessibleDialog';
import AdminLayout from '@/components/AdminLayout';
import QuizAuthoringForm from '@/components/QuizAuthoringForm';
import { adminLessons, adminQuizzes, type AdminLesson, type AdminQuiz, type PageMeta, type QuizWrite } from '@/lib/api';

const blank = (lessonId = 0): QuizWrite => ({ lesson_id: lessonId, title: '', passing_score: 70, status: 'draft', questions: [{ content: '', explanation: '', answers: [{ content: '', is_correct: true }, { content: '', is_correct: false }] }] });
export default function Page() { return <AdminLayout title="Quiz management"><Suspense fallback={<p>Loading quizzes…</p>}><Content /></Suspense></AdminLayout>; }

function Content() {
  const query = useSearchParams(), router = useRouter(), pathname = usePathname();
  const [items, setItems] = useState<AdminQuiz[]>([]), [lessons, setLessons] = useState<AdminLesson[]>([]), [editing, setEditing] = useState<AdminQuiz | null | undefined>(), [deleting, setDeleting] = useState<AdminQuiz>(), [meta, setMeta] = useState<PageMeta>(), [message, setMessage] = useState(''), [loading, setLoading] = useState(true), [deleteBusy, setDeleteBusy] = useState(false);
  const lessonId = Number(query.get('lesson_id') || 0), search = query.get('search') || '', status = query.get('status') || '', page = Number(query.get('page') || 1), mode = query.get('mode');
  const setQuery = useCallback((patch: Record<string, string>) => { const next = new URLSearchParams(query); Object.entries(patch).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); router.replace(`${pathname}?${next}`); }, [pathname, query, router]);
  const load = useCallback(async () => { setLoading(true); setMessage(''); try { const [quizzes, lessonPage] = await Promise.all([adminQuizzes.list({ search, lessonId: lessonId || undefined, status: status || undefined, page }), adminLessons.list({ perPage: 100 })]); setItems(quizzes.data); setMeta(quizzes.meta); setLessons(lessonPage.data); const id = Number(query.get('quiz') || 0); if (mode === 'create') setEditing(null); else if (id) setEditing(await adminQuizzes.get(id)); else setEditing(undefined); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load quizzes.'); } finally { setLoading(false); } }, [lessonId, mode, page, query, search, status]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function save(data: QuizWrite) { if (editing?.id) await adminQuizzes.update(editing.id, data); else await adminQuizzes.create(data); setQuery({ quiz: '', mode: '' }); await load(); }
  async function remove() { if (!deleting) return; setDeleteBusy(true); setMessage(''); try { await adminQuizzes.delete(deleting.id); setDeleting(undefined); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not delete quiz.'); } finally { setDeleteBusy(false); } }
  const close = () => { setEditing(undefined); setQuery({ quiz: '', mode: '' }); };

  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#843ab4]">Assessment studio</p><h1 className="mt-2 text-3xl font-black">Quiz management</h1><p className="text-[#3e4850]">Author questions here; review performance in analytics.</p></div><div className="flex gap-3"><Link href="/quizzes" className="rounded-xl border-2 px-5 py-3 font-bold">View analytics</Link><button onClick={() => setQuery({ mode: 'create', quiz: '' })} className="rounded-xl bg-[#006590] px-5 py-3 font-black text-white">New quiz</button></div></header>
    {message && <p role="alert" className="rounded-xl bg-[#ffdf92] p-3">{message}</p>}
    <div className="grid gap-3 rounded-2xl border-2 bg-white p-4 md:grid-cols-3"><input aria-label="Search quizzes" value={search} onChange={event => setQuery({ search: event.target.value, page: '' })} placeholder="Search quizzes…" className="rounded-xl border-2 p-3"/><select aria-label="Filter by lesson" value={lessonId || ''} onChange={event => setQuery({ lesson_id: event.target.value, page: '' })} className="rounded-xl border-2 p-3"><option value="">All lessons</option>{lessons.map(lesson => <option key={lesson.id} value={lesson.id}>{lesson.title}</option>)}</select><select aria-label="Filter by status" value={status} onChange={event => setQuery({ status: event.target.value, page: '' })} className="rounded-xl border-2 p-3"><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div>
    <section className="overflow-x-auto rounded-3xl border-2 bg-white">{loading ? <p className="p-10 text-center">Loading…</p> : items.length === 0 ? <p className="p-10 text-center">No quizzes found.</p> : <table className="w-full min-w-[720px] text-left"><thead><tr>{['Quiz', 'Lesson', 'Status', 'Questions', 'Attempts', 'Actions'].map(label => <th key={label} className="p-4 text-xs uppercase">{label}</th>)}</tr></thead><tbody>{items.map(item => <tr key={item.id} className="border-t"><td className="p-4 font-black">{item.title}</td><td>{item.lesson.title}</td><td>{item.status}</td><td>{item.questions_count ?? 0}</td><td>{item.attempts_count ?? 0}</td><td><button onClick={() => setQuery({ quiz: String(item.id), mode: 'view' })}>View</button> · <button onClick={() => setQuery({ quiz: String(item.id), mode: 'edit' })} className="text-[#006590]">Edit</button> · <button onClick={() => setDeleting(item)} className="text-[#ba1a1a]">Delete</button></td></tr>)}</tbody></table>}</section>
    <nav aria-label="Quiz pages" className="flex justify-center gap-3"><button disabled={page <= 1} onClick={() => setQuery({ page: String(page - 1) })}>Previous</button><span>{page}/{meta?.last_page ?? 1}</span><button disabled={page >= (meta?.last_page ?? 1)} onClick={() => setQuery({ page: String(page + 1) })}>Next</button></nav>
    {editing && mode === 'view' && <AccessibleDialog title={editing.title} onClose={close} className="max-w-xl"><p className="mt-2">{editing.lesson.title} · {editing.status} · pass {editing.passing_score}%</p><p className="mt-4 font-bold">{editing.questions.length} questions</p><button onClick={close} className="mt-6 rounded-xl border-2 px-5 py-3 font-bold">Close</button></AccessibleDialog>}
    {editing !== undefined && mode !== 'view' && <QuizAuthoringForm initial={editing ?? blank(lessonId)} lessons={lessons} onSave={save} onClose={close}/>} 
    {deleting && <AccessibleDialog title={`Delete “${deleting.title}”?`} description="This permanently removes the quiz when no attempts depend on it." onClose={() => { if (!deleteBusy) setDeleting(undefined); }} className="max-w-md"><div className="mt-6 flex justify-end gap-3"><button disabled={deleteBusy} onClick={() => setDeleting(undefined)}>Cancel</button><button disabled={deleteBusy} onClick={() => void remove()} className="rounded-xl bg-[#ba1a1a] px-5 py-3 font-bold text-white">{deleteBusy ? 'Deleting…' : 'Delete quiz'}</button></div></AccessibleDialog>}
  </div>;
}
